### ISSUE TITLE
Screen width switch bug

### ISSUE THREAD

**Issue by marthesselink** [ahmednooor/halkaBox.js#2]
When trying the demo page it works fine on mobile until you switch between views. You have to refresh the page in order to being able to swipe again. This also happens when resizing the screen in responsive mode using your regular browser.

**Comment by ahmednooor** [comment]
@marthesselink hi, that is because i store the window.innerWidth as a viewport variable so that when a screen is zoomed on mobile or touch device swiping left or right does not jump to next or previous image in the zoomed mode. And when it zooms out to its default width the swipe to next or previous starts working. When the view has is changed from vertical to horizontal the new window.innerWidth does not equals with the viewport anymore thus resulting in no swipe to next/previous. if i remove this functionality zooming will either not be possible or very buggy and when you slide a zoomed image to view other parts of the image,, it instead will jump to next/previous images. An alternative could be to switch on the next previous buttons when the new window.innerWidth is not equal to viewport. Since I myself is in the process of learning JS, I will try to provide a working solution for this problem as i learn more. Thanks a lot for your input.

You can read the code regarding touch at the following link from line 295
https://github.com/ahmednooor/halkaBox.js/blob/master/src/halkaBox.js

**Comment by ahmednooor** [comment]
[halkaBox.zip](https://github.com/ahmednooor/halkaBox.js/files/613055/halkaBox.zip)

@marthesselink  please see the attached zip and use the JS file inside and check if it resolves the issue.
Thanks.

**Comment by ahmednooor** [comment]
@marthesselink  Please check the new url below and let me know if the bug has been fixed. thanks.

https://ahmednooor.github.io/halkaBox.js/testing/

**Comment by marthesselink** [comment]
It's working great right now. Nice fix!

**Comment by ahmednooor** [comment]
@marthesselink  thanks a lot. and thank you for your input :)
