### ISSUE TITLE
Append description of image

### ISSUE THREAD

**Issue by manouman** [ahmednooor/halkaBox.js#7]
It's possible to append the alt attribute after image? Like a legend of the image itself.

**Comment by ahmednooor** [comment]
@manouman   yes you can add `alt` or `title` attributes but the script as of yet wont change it into caption in the lightbox overlay. but the `alt` and `title` attributes will be applied nonetheless according to the browser implemented specifications.

**Comment by ooloth** [comment]
Would love to see this caption feature added. Adding visible image credits to the lightbox is necessary for most of my projects.

**Comment by ahmednooor** [comment]
@ooloth   @manouman   

Thank you for your input. I have added the caption feature. Please visit the following link and test it and share your feedback. Thank you.

https://ahmednooor.github.io/halkaBox.js/testing

**Comment by ooloth** [comment]
I'm impressed! Thanks for the quick turnaround.

The captions work great. The points you mentioned tested well in Safari, Chrome, Firefox and iOS Safari (single touch hides the caption and buttons, zooming works on mobile).

There is a slight difference in how the captions line up with the bottom of the image depending on whether the iOS Safari bottom bar is showing (see the following screenshots). Not sure if that's fixable:

![img_1959](https://user-images.githubusercontent.com/625364/31420709-2f793ea2-ae11-11e7-8a05-f84bcfc41eb1.PNG)
![img_1961](https://user-images.githubusercontent.com/625364/31420710-2fa1c48a-ae11-11e7-87b6-81263f9d7564.PNG)

An option to position the caption directly below the image (instead of at the bottom of the screen) would be lovely, but it also works great without it.

Thanks again!

**Comment by ahmednooor** [comment]
@ooloth   thanks a lot for the detailed test. the caption is position fixed to the bottom and have a semi opaque background that is why when the bottom bar of the safari appears, the screen height shortens and hence the caption moves over the image. Regarding "An option to position the caption directly below the image (instead of at the bottom of the screen)", if that is done then the height of the image will decrease relative to the height of the caption and i haven't added a custom zooming functionality that can work on desktop, yet. so this is not a viable option.
Once again thanks a lot for your input.

**Comment by ahmednooor** [comment]
Features added in version 1.0.0
https://github.com/ahmednooor/halkaBox.js/releases/tag/1.0.0
